build(travis config): manually create mysql docker container and create the "users" database
Switch to using a mysql docker container rather than travis' mysql service because the
"before_install" command: "mysql -e 'CREATE DATABASE IF NOT EXISTS users;'" fails on Windows with
error: "mysql: command not found"